sudo: required
services:
    - docker

before install:
    - docker build -t sandeepsbais/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true sandeepsbais/docker-react npm run test -- --coverage

language: generic